### ISSUE TITLE
CONTACT US 內文字字級及粗細

### ISSUE THREAD

**Issue by katiechoupapa** [sexyoung/sexyoung.github.io#11]
We are accepting new projects----- 此小標題字級25pix， 字體Lato regular
以下內文字級18pix，字體Lato light， 整段連同上面小標題行距30pix
Property developers, Local and international.
Scheracon connects profitable investors to award winning and property developments in Australia.

欄位標題字體都用 Lato light 字級不變
icon旁的phoneXXX & mailXXX 欄位標題字體都用 Lato light 字級不變

**Comment by sexyoung** [comment]
done.
