### ISSUE TITLE
Projects 黑色背景整個區塊縮小至高度950pix/ slider 高度等比縮小至550pix/ 兩邊箭頭不壓圖並縮小50%

### ISSUE THREAD

**Issue by katiechoupapa** [sexyoung/sexyoung.github.io#13]
![2018-05-30 1 45 28](https://user-images.githubusercontent.com/39607944/40671331-eb75ef4e-63ae-11e8-8315-ec1ec250e2e6.png)
![2018-05-30 1 46 05](https://user-images.githubusercontent.com/39607944/40671332-ebb1ee5e-63ae-11e8-8f7e-dfedaabfde5f.png)

**Comment by sexyoung** [comment]
done.
